runtime: nodejs20
entrypoint: node build/app.js
instance_class: F1

env_variables:
  NODE_ENV: 'production'
  PORT: '3000'
  API_URL: 'https://jsonplaceholder.typicode.com/'

handlers:
  - url: /.*
    static_dir: public
